networks:
  tidefly_internal:
    name: tidefly_internal
    driver: bridge
    labels:
      tidefly.internal: "true"
    ipam:
      config:
        - subnet: 172.30.0.0/24
  tidefly_proxy:
    name: tidefly_proxy
    driver: bridge
    labels:
      tidefly.internal: "true"
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  postgres_data:
    name: tidefly_postgres_data
  redis_data:
    name: tidefly_redis_data
  mailpit_data:
    name: tidefly_mailpit_data
  caddy_data:
    name: tidefly_caddy_data

services:
  caddy:
    image: ghcr.io/tidefly-oss/tidefly-caddy:0.0.1
    container_name: tidefly_caddy
    labels:
      tidefly.internal: "true"
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-10080}:80"
      - "${CADDY_HTTPS_PORT:-10443}:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - caddy_data:/data
    networks:
      - tidefly_proxy
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    command: caddy run --resume
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:2019/config/" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # -----------------------------
  # PostgreSQL
  # -----------------------------
  postgres:
    image: postgres:18-alpine
    container_name: tidefly_postgres
    labels:
      tidefly.internal: "true"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - tidefly_internal
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tidefly-plane} -d ${POSTGRES_DB:-tidefly-plane}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -----------------------------
  # Redis
  # -----------------------------
  redis:
    image: redis:8-alpine
    container_name: tidefly_redis
    labels:
      tidefly.internal: "true"
    restart: unless-stopped
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
      - ./redis:/usr/local/etc/redis
    networks:
      - tidefly_internal
    ports:
      - "${REDIS_PORT:-16379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--user", "tidefly-plane", "--pass", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # -----------------------------
  # Mailpit SMTP & Web UI
  # -----------------------------
  mailpit:
    image: axllent/mailpit:latest
    container_name: tidefly_mailpit
    labels:
      tidefly.internal: "true"
    restart: unless-stopped
    networks:
      - tidefly_internal
    ports:
      - "${MAILPIT_SMTP_PORT:-11025}:1025"
      - "${MAILPIT_WEB_PORT:-18025}:8025"