networks:
  tidefly_internal:
    name: tidefly_internal_dev
    driver: bridge
  tidefly_proxy:
    name: tidefly_proxy_dev
    driver: bridge

volumes:
  postgres_data:
    name: tidefly_postgres_data_dev
  redis_data:
    name: tidefly_redis_data_dev
  caddy_data:
    name: tidefly_caddy_data_dev

services:
  caddy:
    image: tidefly/tidefly-caddy:latest
    container_name: tidefly_caddy_dev
    labels:
      tidefly.internal: "true"
    restart: "no"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - caddy_data:/data
    networks:
      - tidefly_proxy
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    command: caddy run --resume
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2019/config/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    image: tidefly/tidefly-plane:latest
    container_name: tidefly_backend_dev
    labels:
      tidefly.internal: "true"
    restart: "no"
    ports:
      - "127.0.0.1:8181:8181"
    env_file:
      - ./.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TIDEFLY_DIR:-${HOME}/.local/share/tidefly-plane}/templates:/home/tidefly/templates
    networks:
      - tidefly_internal
      - tidefly_proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      caddy:
        condition: service_healthy

  ui:
    image: tidefly/tidefly-ui:latest
    container_name: tidefly_ui_dev
    labels:
      tidefly.internal: "true"
    restart: "no"
    env_file:
      - ./.env.dev
    networks:
      - tidefly_internal
    depends_on:
      - backend
    profiles:
      - dashboard

  postgres:
    image: postgres:18-alpine
    container_name: tidefly_postgres_dev
    labels:
      tidefly.internal: "true"
    restart: "no"
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - tidefly_internal
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-tidefly} -d ${POSTGRES_DB:-tidefly}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8-alpine
    container_name: tidefly_redis_dev
    labels:
      tidefly.internal: "true"
    restart: "no"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    env_file:
      - ./.env.dev
    volumes:
      - redis_data:/data
      - ./redis:/usr/local/etc/redis
    networks:
      - tidefly_internal
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--user",
          "tidefly",
          "--pass",
          "${REDIS_PASSWORD}",
          "ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
