package pages

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
)

func navigate(page Page, cfg SetupConfig) tea.Cmd {
	return func() tea.Msg { return NavigateTo{Page: page, Config: cfg} }
}

func generateSecrets() (string, error) {
	appSecret, err := randomHex(32)
	if err != nil {
		return "", fmt.Errorf("failed to generate app secret: %w", err)
	}
	jwtSecret, err := randomHex(32)
	if err != nil {
		return "", fmt.Errorf("failed to generate jwt secret: %w", err)
	}
	encKey, err := randomBase64(32)
	if err != nil {
		return "", fmt.Errorf("failed to generate encryption key: %w", err)
	}
	pgPass, err := randomBase64(48)
	if err != nil {
		return "", fmt.Errorf("failed to generate postgres password: %w", err)
	}
	redisPass, err := randomBase64(48)
	if err != nil {
		return "", fmt.Errorf("failed to generate redis password: %w", err)
	}

	pgPass = sanitizePassword(pgPass)
	redisPass = sanitizePassword(redisPass)

	env := fmt.Sprintf(`# Generated by tidefly-tui
# DO NOT COMMIT THIS FILE

# ── App ──────────────────────────────────────────────────────────────
APP_ENV=production
APP_PORT=8181
APP_SECRET_KEY=%s
API_DOCS_ENABLED=false
TIDEFLY_ENCRYPTION_KEY=%s
AGENT_GRPC_PORT=7443

# ── Database ─────────────────────────────────────────────────────────
DATABASE_URL=postgres://tidefly:%s@postgres:5432/tidefly?sslmode=disable
POSTGRES_USER=tidefly
POSTGRES_PASSWORD=%s
POSTGRES_DB=tidefly

# ── Redis ────────────────────────────────────────────────────────────
REDIS_URL=redis://tidefly:%s@redis:6379/0
REDIS_ADDR=redis:6379
REDIS_USER=tidefly
REDIS_PASSWORD=%s

# ── Auth ─────────────────────────────────────────────────────────────
JWT_SECRET=%s

# ── Docker Runtime ───────────────────────────────────────────────────
RUNTIME_TYPE=docker
DOCKER_SOCK=/var/run/docker.sock
RUNTIME_SOCKET=/var/run/docker.sock

# ── SMTP (optional) ──────────────────────────────────────────────────
SMTP_HOST=smtp.example.com
SMTP_PORT=465
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=noreply@example.com
SMTP_TLS=tls

# ── Caddy ────────────────────────────────────────────────────────────
CADDY_ENABLED=true
CADDY_ADMIN_URL=http://caddy:2019
CADDY_BASE_DOMAIN=apps.example.com
CADDY_ACME_EMAIL=admin@example.com
CADDY_ACME_STAGING=false
CADDY_FORCE_HTTPS=true
CADDY_INTERNAL_TLS=true

# ── Logging ──────────────────────────────────────────────────────────
LOG_LEVEL=info
LOG_DB_LEVEL=warn
LOG_SLOW_QUERY_MS=500

# ── Log Watcher ──────────────────────────────────────────────────────
LOGWATCHER_ENABLED=true
LOGWATCHER_POLL_INTERVAL=15
LOGWATCHER_TAIL_LINES=50
LOGWATCHER_MAX_MESSAGE_LEN=3000
LOGWATCHER_DEDUP_WINDOW=2

# ── Jobs ─────────────────────────────────────────────────────────────
JOBS_ENABLED=true
JOBS_CLEANUP_CRON=0 3 * * *
JOBS_CLEANUP_OLDER_THAN=24h
JOBS_CLEANUP_STOPPED_CONTAINERS=true
JOBS_CLEANUP_DANGLING_IMAGES=true
JOBS_CLEANUP_UNUSED_VOLUMES=false
JOBS_LOG_RETENTION_CRON=0 4 * * *
JOBS_LOG_RETENTION_DAYS=30
JOBS_AUDIT_RETENTION_DAYS=90
JOBS_NOTIFICATION_RETENTION_DAYS=30
JOBS_HEALTH_CHECK_CRON=*/5 * * * *
JOBS_CONCURRENCY=5
`,
		appSecret, encKey,
		pgPass, pgPass,
		redisPass, redisPass,
		jwtSecret,
	)

	return env, nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func randomBase64(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

func sanitizePassword(s string) string {
	s = strings.ReplaceAll(s, "=", "")
	s = strings.ReplaceAll(s, "/", "")
	s = strings.ReplaceAll(s, "+", "")
	if len(s) > 48 {
		s = s[:48]
	}
	return s
}
